apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: dockerize-deployment
spec:
  selector:
    matchLabels:
      app: dockerize
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: dockerize
    spec:
      containers:
        - name: dockerize
          image: be4929/dockerize # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 9000 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: dockerize-service
spec:
  selector:
    app: dockerize
  ports:
    - protocol: "TCP"
      port: 9000 # The port that the service is running on in the cluster
      targetPort: 9000 # The port exposed by the service
  type: NodePort # type of the service.